### ISSUE TITLE
Problem to create a standalone executable

### ISSUE THREAD

**Issue by nathalierun** [Rydion/Snapp#14] opened 2017-02-05 15:43 UTC
Hello,

I keep on having problem to create some standalone executables files with snapp (related here https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1527).

It happened with this file :
https://snap.berkeley.edu/snapsource/snap.html#cloud:Username=nathalierun&ProjectName=ChasseAuTresor.Simulation

I tried both with Firefox and Chrome, on Mac OS 10.11.6 (64 bits).

**Comment by Rydion** [comment] 2017-02-05 15:49
Hi, I've just tested it and it seems to work properly. Could you go into a little bit more detail of what the issue is? Isn't the file downloading for you at all? Or is the project not working as expected when executing it?

**Comment by nathalierun** [comment] 2017-02-06 14:47
Hi,
The file's downloading is ok. But the project crashes immediatly when executing it (after having dezipped it) : I see the Lambda symbol attached to the application in the lateral desk, but it disappears immediatly.

**Comment by Rydion** [comment] 2017-02-06 17:46
Hi,

maybe some of the workarounds for Mac got lost in an update. I'll check it
today.
I'm sorry that Mac OS has so many issues but without owning one myself it's
difficult to debug.

**Comment by Rydion** [comment] 2017-02-07 19:35
Hi,

so I haven't seen anything strange. I have made the fix from the other issue a bit stricter to see if it helps.

As I don't have a Mac could you please try a few things out for me?. If you currently can't just let me know and I will ask the guys over at Snap!.

1 - Try a different project and see if it works.
2 - Try this project once again and see if it works.
3 - Try this project once again but before exporting it as XML remove the "." from the project name and filename. It should only be called "ChasseAuTresor"

Thank you

**Comment by nathalierun** [comment] 2017-02-09 09:26
Le 07/02/2017 à 23:35, Adrian Hintze a écrit :
> 1 - Try a different project and see if it works.

Hi,
The first point doesn't work.
The zipped file is downloaded correctly. But, when I launch the 
application uncompressed, it crashes immediatly.

**Comment by nathalierun** [comment] 2017-02-09 10:11
Le 07/02/2017 à 23:35, Adrian Hintze a écrit :
> 3 - Try this project once again but before exporting it as XML remove
> the "." from the project name and filename.

I tried this also. It reacts with the same crash.

**Comment by Rydion** [comment] 2017-02-09 16:51
Hi,

thank you for testing. Has any project worked for you at all since the bug
fix discussed in the Snap! issue? If yes has anything changed on your end
in the meantime? Maybe some OS update or something similar.

**Comment by Rydion** [comment] 2017-02-13 01:31
Hi,

I was able to get my hands on a Mac and figured out the issue. Everything should be working again.

I'll try to make the mac executable generation more robust while I have the mac available and hopefully this will help with avoiding this kind of problems in the future.

Please notify me once you've confirmed it works on your end also and I'll close the issue.

**Comment by nathalierun** [comment] 2017-02-13 13:11
Hi,

Nice !!! I confirm that it works ! I tested several projects.

I just notice that :

- The characters are fuzzy

<img width="263" alt="capture d ecran 2017-02-13 a 17 01 38" src="https://cloud.githubusercontent.com/assets/17542520/22884550/f2ce591a-f20e-11e6-824d-3aa7f081127b.png">

<img width="880" alt="capture d ecran 2017-02-13 a 17 00 20" src="https://cloud.githubusercontent.com/assets/17542520/22884556/f9097fe4-f20e-11e6-8700-7c6683766902.png">

- we cannot exit with the keyboard shortcut 

<img width="263" alt="capture d ecran 2017-02-13 a 17 01 38" src="https://cloud.githubusercontent.com/assets/17542520/22884609/343c032a-f20f-11e6-8a0d-63927b752e2d.png">

**Comment by Rydion** [comment] 2017-02-15 00:57
Hi,

the fuziness of the text is due to Snap's retina display support currently being disabled in Snapp. This is due to a incompatibility with the software used to generate the executable. I more or less know what to do to fix it but it will be a while 'til I have time to fix it.

As for the shortcut I just tested with macOS Sierra (10.12.2) and everything worked as expected. Was there a problem only when using the shortcut or also when using the menu?

**Closed** 2017-04-30 21:11 UTC
Labels: bug
